# Generated by Django 4.0.5 on 2022-06-21 03:57

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('bnb_kingdom_api', '0002_rename_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyhistory',
            name='created_at',
            field=models.FloatField(default=time.time),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.FloatField(default=time.time),
        ),
    ]
